/*
 * Lob
 *
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using lob.dotnet.Client;
using System.Runtime.Serialization;
using lob.dotnet.Model;

namespace lob.dotnet.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBuckslipOrdersApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// create
        /// </summary>
        /// <remarks>
        /// Creates a new buckslip order given information
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="buckslipId">The ID of the buckslip to which the buckslip orders belong.</param>
        /// <param name="buckslipOrderEditable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BuckslipOrder</returns>
        BuckslipOrder create(string buckslipId, BuckslipOrderEditable buckslipOrderEditable, int operationIndex = 0);

        /// <summary>
        /// create
        /// </summary>
        /// <remarks>
        /// Creates a new buckslip order given information
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="buckslipId">The ID of the buckslip to which the buckslip orders belong.</param>
        /// <param name="buckslipOrderEditable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BuckslipOrder</returns>
        ApiResponse<BuckslipOrder> createWithHttpInfo(string buckslipId, BuckslipOrderEditable buckslipOrderEditable, int operationIndex = 0);
        /// <summary>
        /// get
        /// </summary>
        /// <remarks>
        /// Retrieves the buckslip orders associated with the given buckslip id.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="buckslipId">The ID of the buckslip to which the buckslip orders belong.</param>
        /// <param name="limit">How many results to return. (optional, default to 10)</param>
        /// <param name="offset">An integer that designates the offset at which to begin returning results. Defaults to 0. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BuckslipOrdersList</returns>
        BuckslipOrdersList get(string buckslipId, int? limit = default(int?), int? offset = default(int?), int operationIndex = 0);

        /// <summary>
        /// get
        /// </summary>
        /// <remarks>
        /// Retrieves the buckslip orders associated with the given buckslip id.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="buckslipId">The ID of the buckslip to which the buckslip orders belong.</param>
        /// <param name="limit">How many results to return. (optional, default to 10)</param>
        /// <param name="offset">An integer that designates the offset at which to begin returning results. Defaults to 0. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BuckslipOrdersList</returns>
        ApiResponse<BuckslipOrdersList> getWithHttpInfo(string buckslipId, int? limit = default(int?), int? offset = default(int?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBuckslipOrdersApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// create
        /// </summary>
        /// <remarks>
        /// Creates a new buckslip order given information
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="buckslipId">The ID of the buckslip to which the buckslip orders belong.</param>
        /// <param name="buckslipOrderEditable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BuckslipOrder</returns>
        System.Threading.Tasks.Task<BuckslipOrder> createAsync(string buckslipId, BuckslipOrderEditable buckslipOrderEditable, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// create
        /// </summary>
        /// <remarks>
        /// Creates a new buckslip order given information
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="buckslipId">The ID of the buckslip to which the buckslip orders belong.</param>
        /// <param name="buckslipOrderEditable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BuckslipOrder)</returns>
        System.Threading.Tasks.Task<ApiResponse<BuckslipOrder>> createWithHttpInfoAsync(string buckslipId, BuckslipOrderEditable buckslipOrderEditable, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// get
        /// </summary>
        /// <remarks>
        /// Retrieves the buckslip orders associated with the given buckslip id.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="buckslipId">The ID of the buckslip to which the buckslip orders belong.</param>
        /// <param name="limit">How many results to return. (optional, default to 10)</param>
        /// <param name="offset">An integer that designates the offset at which to begin returning results. Defaults to 0. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BuckslipOrdersList</returns>
        System.Threading.Tasks.Task<BuckslipOrdersList> getAsync(string buckslipId, int? limit = default(int?), int? offset = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// get
        /// </summary>
        /// <remarks>
        /// Retrieves the buckslip orders associated with the given buckslip id.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="buckslipId">The ID of the buckslip to which the buckslip orders belong.</param>
        /// <param name="limit">How many results to return. (optional, default to 10)</param>
        /// <param name="offset">An integer that designates the offset at which to begin returning results. Defaults to 0. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BuckslipOrdersList)</returns>
        System.Threading.Tasks.Task<ApiResponse<BuckslipOrdersList>> getWithHttpInfoAsync(string buckslipId, int? limit = default(int?), int? offset = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBuckslipOrdersApi : IBuckslipOrdersApiSync, IBuckslipOrdersApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class BuckslipOrdersApi : IBuckslipOrdersApi
    {
        private lob.dotnet.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="BuckslipOrdersApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BuckslipOrdersApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BuckslipOrdersApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BuckslipOrdersApi(string basePath)
        {
            this.Configuration = lob.dotnet.Client.Configuration.MergeConfigurations(
                lob.dotnet.Client.GlobalConfiguration.Instance,
                new lob.dotnet.Client.Configuration { BasePath = basePath }
            );
            this.Client = new lob.dotnet.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new lob.dotnet.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = lob.dotnet.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BuckslipOrdersApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public BuckslipOrdersApi(lob.dotnet.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = lob.dotnet.Client.Configuration.MergeConfigurations(
                lob.dotnet.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new lob.dotnet.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new lob.dotnet.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = lob.dotnet.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BuckslipOrdersApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public BuckslipOrdersApi(lob.dotnet.Client.ISynchronousClient client, lob.dotnet.Client.IAsynchronousClient asyncClient, lob.dotnet.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = lob.dotnet.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public lob.dotnet.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public lob.dotnet.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public lob.dotnet.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public lob.dotnet.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// create Creates a new buckslip order given information
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="buckslipId">The ID of the buckslip to which the buckslip orders belong.</param>
        /// <param name="buckslipOrderEditable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BuckslipOrder</returns>
        public BuckslipOrder create(string buckslipId, BuckslipOrderEditable buckslipOrderEditable, int operationIndex = 0)
        {
            lob.dotnet.Client.ApiResponse<BuckslipOrder> localVarResponse = createWithHttpInfo(buckslipId, buckslipOrderEditable);
            return localVarResponse.Data;
        }

        /// <summary>
        /// create Creates a new buckslip order given information
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="buckslipId">The ID of the buckslip to which the buckslip orders belong.</param>
        /// <param name="buckslipOrderEditable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BuckslipOrder</returns>
        public lob.dotnet.Client.ApiResponse<BuckslipOrder> createWithHttpInfo(string buckslipId, BuckslipOrderEditable buckslipOrderEditable, int operationIndex = 0)
        {
            // verify the required parameter 'buckslipId' is set
            if (buckslipId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'buckslipId' when calling BuckslipOrdersApi->create");
            }

            // verify the required parameter 'buckslipOrderEditable' is set
            if (buckslipOrderEditable == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'buckslipOrderEditable' when calling BuckslipOrdersApi->create");
            }

            lob.dotnet.Client.RequestOptions localVarRequestOptions = new lob.dotnet.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "application/x-www-form-urlencoded",
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = lob.dotnet.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = lob.dotnet.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("buckslip_id", lob.dotnet.Client.ClientUtils.ParameterToString(buckslipId)); // path parameter
            localVarRequestOptions.Data = buckslipOrderEditable;

            localVarRequestOptions.Operation = "BuckslipOrdersApi.create";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + lob.dotnet.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<BuckslipOrder>("/buckslips/{buckslip_id}/orders", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("create", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// create Creates a new buckslip order given information
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="buckslipId">The ID of the buckslip to which the buckslip orders belong.</param>
        /// <param name="buckslipOrderEditable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BuckslipOrder</returns>
        public async System.Threading.Tasks.Task<BuckslipOrder> createAsync(string buckslipId, BuckslipOrderEditable buckslipOrderEditable, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            lob.dotnet.Client.ApiResponse<BuckslipOrder> localVarResponse = await createWithHttpInfoAsync(buckslipId, buckslipOrderEditable, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// create Creates a new buckslip order given information
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="buckslipId">The ID of the buckslip to which the buckslip orders belong.</param>
        /// <param name="buckslipOrderEditable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BuckslipOrder)</returns>
        public async System.Threading.Tasks.Task<lob.dotnet.Client.ApiResponse<BuckslipOrder>> createWithHttpInfoAsync(string buckslipId, BuckslipOrderEditable buckslipOrderEditable, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'buckslipId' is set
            if (buckslipId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'buckslipId' when calling BuckslipOrdersApi->create");
            }

            // verify the required parameter 'buckslipOrderEditable' is set
            if (buckslipOrderEditable == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'buckslipOrderEditable' when calling BuckslipOrdersApi->create");
            }


            lob.dotnet.Client.RequestOptions localVarRequestOptions = new lob.dotnet.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "application/x-www-form-urlencoded", 
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = lob.dotnet.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = lob.dotnet.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("buckslip_id", lob.dotnet.Client.ClientUtils.ParameterToString(buckslipId)); // path parameter
            localVarRequestOptions.Data = buckslipOrderEditable;

            localVarRequestOptions.Operation = "BuckslipOrdersApi.create";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + lob.dotnet.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<BuckslipOrder>("/buckslips/{buckslip_id}/orders", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("create", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// get Retrieves the buckslip orders associated with the given buckslip id.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="buckslipId">The ID of the buckslip to which the buckslip orders belong.</param>
        /// <param name="limit">How many results to return. (optional, default to 10)</param>
        /// <param name="offset">An integer that designates the offset at which to begin returning results. Defaults to 0. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BuckslipOrdersList</returns>
        public BuckslipOrdersList get(string buckslipId, int? limit = default(int?), int? offset = default(int?), int operationIndex = 0)
        {
            lob.dotnet.Client.ApiResponse<BuckslipOrdersList> localVarResponse = getWithHttpInfo(buckslipId, limit, offset);
            return localVarResponse.Data;
        }

        /// <summary>
        /// get Retrieves the buckslip orders associated with the given buckslip id.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="buckslipId">The ID of the buckslip to which the buckslip orders belong.</param>
        /// <param name="limit">How many results to return. (optional, default to 10)</param>
        /// <param name="offset">An integer that designates the offset at which to begin returning results. Defaults to 0. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BuckslipOrdersList</returns>
        public lob.dotnet.Client.ApiResponse<BuckslipOrdersList> getWithHttpInfo(string buckslipId, int? limit = default(int?), int? offset = default(int?), int operationIndex = 0)
        {
            // verify the required parameter 'buckslipId' is set
            if (buckslipId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'buckslipId' when calling BuckslipOrdersApi->get");
            }

            lob.dotnet.Client.RequestOptions localVarRequestOptions = new lob.dotnet.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = lob.dotnet.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = lob.dotnet.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("buckslip_id", lob.dotnet.Client.ClientUtils.ParameterToString(buckslipId)); // path parameter
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(lob.dotnet.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(lob.dotnet.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }

            localVarRequestOptions.Operation = "BuckslipOrdersApi.get";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + lob.dotnet.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<BuckslipOrdersList>("/buckslips/{buckslip_id}/orders", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("get", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// get Retrieves the buckslip orders associated with the given buckslip id.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="buckslipId">The ID of the buckslip to which the buckslip orders belong.</param>
        /// <param name="limit">How many results to return. (optional, default to 10)</param>
        /// <param name="offset">An integer that designates the offset at which to begin returning results. Defaults to 0. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BuckslipOrdersList</returns>
        public async System.Threading.Tasks.Task<BuckslipOrdersList> getAsync(string buckslipId, int? limit = default(int?), int? offset = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            lob.dotnet.Client.ApiResponse<BuckslipOrdersList> localVarResponse = await getWithHttpInfoAsync(buckslipId, limit, offset, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// get Retrieves the buckslip orders associated with the given buckslip id.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="buckslipId">The ID of the buckslip to which the buckslip orders belong.</param>
        /// <param name="limit">How many results to return. (optional, default to 10)</param>
        /// <param name="offset">An integer that designates the offset at which to begin returning results. Defaults to 0. (optional, default to 0)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BuckslipOrdersList)</returns>
        public async System.Threading.Tasks.Task<lob.dotnet.Client.ApiResponse<BuckslipOrdersList>> getWithHttpInfoAsync(string buckslipId, int? limit = default(int?), int? offset = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'buckslipId' is set
            if (buckslipId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'buckslipId' when calling BuckslipOrdersApi->get");
            }


            lob.dotnet.Client.RequestOptions localVarRequestOptions = new lob.dotnet.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = lob.dotnet.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = lob.dotnet.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("buckslip_id", lob.dotnet.Client.ClientUtils.ParameterToString(buckslipId)); // path parameter
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(lob.dotnet.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(lob.dotnet.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }

            localVarRequestOptions.Operation = "BuckslipOrdersApi.get";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + lob.dotnet.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<BuckslipOrdersList>("/buckslips/{buckslip_id}/orders", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("get", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
