/*
 * Lob
 *
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using lob.dotnet.Client;
using System.Runtime.Serialization;
using lob.dotnet.Model;

namespace lob.dotnet.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITemplateVersionsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// create
        /// </summary>
        /// <remarks>
        /// Creates a new template version attached to the specified template.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template the new version will be attached to</param>
        /// <param name="templateVersionWritable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TemplateVersion</returns>
        TemplateVersion create(string tmplId, TemplateVersionWritable templateVersionWritable, int operationIndex = 0);

        /// <summary>
        /// create
        /// </summary>
        /// <remarks>
        /// Creates a new template version attached to the specified template.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template the new version will be attached to</param>
        /// <param name="templateVersionWritable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TemplateVersion</returns>
        ApiResponse<TemplateVersion> createWithHttpInfo(string tmplId, TemplateVersionWritable templateVersionWritable, int operationIndex = 0);
        /// <summary>
        /// delete
        /// </summary>
        /// <remarks>
        /// Permanently deletes a template version. A template&#39;s &#x60;published_version&#x60; can not be deleted.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TemplateVersionDeletion</returns>
        TemplateVersionDeletion delete(string tmplId, string vrsnId, int operationIndex = 0);

        /// <summary>
        /// delete
        /// </summary>
        /// <remarks>
        /// Permanently deletes a template version. A template&#39;s &#x60;published_version&#x60; can not be deleted.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TemplateVersionDeletion</returns>
        ApiResponse<TemplateVersionDeletion> deleteWithHttpInfo(string tmplId, string vrsnId, int operationIndex = 0);
        /// <summary>
        /// get
        /// </summary>
        /// <remarks>
        /// Retrieves the template version with the given template and version ids.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TemplateVersion</returns>
        TemplateVersion get(string tmplId, string vrsnId, int operationIndex = 0);

        /// <summary>
        /// get
        /// </summary>
        /// <remarks>
        /// Retrieves the template version with the given template and version ids.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TemplateVersion</returns>
        ApiResponse<TemplateVersion> getWithHttpInfo(string tmplId, string vrsnId, int operationIndex = 0);
        /// <summary>
        /// update
        /// </summary>
        /// <remarks>
        /// Updates the template version with the given template and version ids.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="templateVersionUpdatable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TemplateVersion</returns>
        TemplateVersion update(string tmplId, string vrsnId, TemplateVersionUpdatable templateVersionUpdatable, int operationIndex = 0);

        /// <summary>
        /// update
        /// </summary>
        /// <remarks>
        /// Updates the template version with the given template and version ids.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="templateVersionUpdatable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TemplateVersion</returns>
        ApiResponse<TemplateVersion> updateWithHttpInfo(string tmplId, string vrsnId, TemplateVersionUpdatable templateVersionUpdatable, int operationIndex = 0);
        /// <summary>
        /// list
        /// </summary>
        /// <remarks>
        /// Returns a list of template versions for the given template ID. The template versions are sorted by creation date, with the most recently created appearing first. 
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template associated with the retrieved versions</param>
        /// <param name="limit">How many results to return. (optional, default to 10)</param>
        /// <param name="before">A reference to a list entry used for paginating to the previous set of entries. This field is pre-populated in the &#x60;previous_url&#x60; field in the return response.  (optional)</param>
        /// <param name="after">A reference to a list entry used for paginating to the next set of entries. This field is pre-populated in the &#x60;next_url&#x60; field in the return response.  (optional)</param>
        /// <param name="include">Request that the response include the total count by specifying &#x60;include[]&#x3D;total_count&#x60;.  (optional)</param>
        /// <param name="dateCreated">Filter by date created. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TemplateVersionList</returns>
        TemplateVersionList list(string tmplId, int? limit = default(int?), string before = default(string), string after = default(string), List<string> include = default(List<string>), Dictionary<string, DateTime> dateCreated = default(Dictionary<string, DateTime>), int operationIndex = 0);

        /// <summary>
        /// list
        /// </summary>
        /// <remarks>
        /// Returns a list of template versions for the given template ID. The template versions are sorted by creation date, with the most recently created appearing first. 
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template associated with the retrieved versions</param>
        /// <param name="limit">How many results to return. (optional, default to 10)</param>
        /// <param name="before">A reference to a list entry used for paginating to the previous set of entries. This field is pre-populated in the &#x60;previous_url&#x60; field in the return response.  (optional)</param>
        /// <param name="after">A reference to a list entry used for paginating to the next set of entries. This field is pre-populated in the &#x60;next_url&#x60; field in the return response.  (optional)</param>
        /// <param name="include">Request that the response include the total count by specifying &#x60;include[]&#x3D;total_count&#x60;.  (optional)</param>
        /// <param name="dateCreated">Filter by date created. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TemplateVersionList</returns>
        ApiResponse<TemplateVersionList> listWithHttpInfo(string tmplId, int? limit = default(int?), string before = default(string), string after = default(string), List<string> include = default(List<string>), Dictionary<string, DateTime> dateCreated = default(Dictionary<string, DateTime>), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITemplateVersionsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// create
        /// </summary>
        /// <remarks>
        /// Creates a new template version attached to the specified template.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template the new version will be attached to</param>
        /// <param name="templateVersionWritable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TemplateVersion</returns>
        System.Threading.Tasks.Task<TemplateVersion> createAsync(string tmplId, TemplateVersionWritable templateVersionWritable, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// create
        /// </summary>
        /// <remarks>
        /// Creates a new template version attached to the specified template.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template the new version will be attached to</param>
        /// <param name="templateVersionWritable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TemplateVersion)</returns>
        System.Threading.Tasks.Task<ApiResponse<TemplateVersion>> createWithHttpInfoAsync(string tmplId, TemplateVersionWritable templateVersionWritable, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// delete
        /// </summary>
        /// <remarks>
        /// Permanently deletes a template version. A template&#39;s &#x60;published_version&#x60; can not be deleted.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TemplateVersionDeletion</returns>
        System.Threading.Tasks.Task<TemplateVersionDeletion> deleteAsync(string tmplId, string vrsnId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// delete
        /// </summary>
        /// <remarks>
        /// Permanently deletes a template version. A template&#39;s &#x60;published_version&#x60; can not be deleted.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TemplateVersionDeletion)</returns>
        System.Threading.Tasks.Task<ApiResponse<TemplateVersionDeletion>> deleteWithHttpInfoAsync(string tmplId, string vrsnId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// get
        /// </summary>
        /// <remarks>
        /// Retrieves the template version with the given template and version ids.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TemplateVersion</returns>
        System.Threading.Tasks.Task<TemplateVersion> getAsync(string tmplId, string vrsnId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// get
        /// </summary>
        /// <remarks>
        /// Retrieves the template version with the given template and version ids.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TemplateVersion)</returns>
        System.Threading.Tasks.Task<ApiResponse<TemplateVersion>> getWithHttpInfoAsync(string tmplId, string vrsnId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// update
        /// </summary>
        /// <remarks>
        /// Updates the template version with the given template and version ids.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="templateVersionUpdatable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TemplateVersion</returns>
        System.Threading.Tasks.Task<TemplateVersion> updateAsync(string tmplId, string vrsnId, TemplateVersionUpdatable templateVersionUpdatable, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// update
        /// </summary>
        /// <remarks>
        /// Updates the template version with the given template and version ids.
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="templateVersionUpdatable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TemplateVersion)</returns>
        System.Threading.Tasks.Task<ApiResponse<TemplateVersion>> updateWithHttpInfoAsync(string tmplId, string vrsnId, TemplateVersionUpdatable templateVersionUpdatable, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// list
        /// </summary>
        /// <remarks>
        /// Returns a list of template versions for the given template ID. The template versions are sorted by creation date, with the most recently created appearing first. 
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template associated with the retrieved versions</param>
        /// <param name="limit">How many results to return. (optional, default to 10)</param>
        /// <param name="before">A reference to a list entry used for paginating to the previous set of entries. This field is pre-populated in the &#x60;previous_url&#x60; field in the return response.  (optional)</param>
        /// <param name="after">A reference to a list entry used for paginating to the next set of entries. This field is pre-populated in the &#x60;next_url&#x60; field in the return response.  (optional)</param>
        /// <param name="include">Request that the response include the total count by specifying &#x60;include[]&#x3D;total_count&#x60;.  (optional)</param>
        /// <param name="dateCreated">Filter by date created. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TemplateVersionList</returns>
        System.Threading.Tasks.Task<TemplateVersionList> listAsync(string tmplId, int? limit = default(int?), string before = default(string), string after = default(string), List<string> include = default(List<string>), Dictionary<string, DateTime> dateCreated = default(Dictionary<string, DateTime>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// list
        /// </summary>
        /// <remarks>
        /// Returns a list of template versions for the given template ID. The template versions are sorted by creation date, with the most recently created appearing first. 
        /// </remarks>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template associated with the retrieved versions</param>
        /// <param name="limit">How many results to return. (optional, default to 10)</param>
        /// <param name="before">A reference to a list entry used for paginating to the previous set of entries. This field is pre-populated in the &#x60;previous_url&#x60; field in the return response.  (optional)</param>
        /// <param name="after">A reference to a list entry used for paginating to the next set of entries. This field is pre-populated in the &#x60;next_url&#x60; field in the return response.  (optional)</param>
        /// <param name="include">Request that the response include the total count by specifying &#x60;include[]&#x3D;total_count&#x60;.  (optional)</param>
        /// <param name="dateCreated">Filter by date created. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TemplateVersionList)</returns>
        System.Threading.Tasks.Task<ApiResponse<TemplateVersionList>> listWithHttpInfoAsync(string tmplId, int? limit = default(int?), string before = default(string), string after = default(string), List<string> include = default(List<string>), Dictionary<string, DateTime> dateCreated = default(Dictionary<string, DateTime>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITemplateVersionsApi : ITemplateVersionsApiSync, ITemplateVersionsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TemplateVersionsApi : ITemplateVersionsApi
    {
        private lob.dotnet.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateVersionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TemplateVersionsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateVersionsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TemplateVersionsApi(string basePath)
        {
            this.Configuration = lob.dotnet.Client.Configuration.MergeConfigurations(
                lob.dotnet.Client.GlobalConfiguration.Instance,
                new lob.dotnet.Client.Configuration { BasePath = basePath }
            );
            this.Client = new lob.dotnet.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new lob.dotnet.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = lob.dotnet.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateVersionsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TemplateVersionsApi(lob.dotnet.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = lob.dotnet.Client.Configuration.MergeConfigurations(
                lob.dotnet.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new lob.dotnet.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new lob.dotnet.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = lob.dotnet.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateVersionsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public TemplateVersionsApi(lob.dotnet.Client.ISynchronousClient client, lob.dotnet.Client.IAsynchronousClient asyncClient, lob.dotnet.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = lob.dotnet.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public lob.dotnet.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public lob.dotnet.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public lob.dotnet.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public lob.dotnet.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// create Creates a new template version attached to the specified template.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template the new version will be attached to</param>
        /// <param name="templateVersionWritable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TemplateVersion</returns>
        public TemplateVersion create(string tmplId, TemplateVersionWritable templateVersionWritable, int operationIndex = 0)
        {
            lob.dotnet.Client.ApiResponse<TemplateVersion> localVarResponse = createWithHttpInfo(tmplId, templateVersionWritable);
            return localVarResponse.Data;
        }

        /// <summary>
        /// create Creates a new template version attached to the specified template.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template the new version will be attached to</param>
        /// <param name="templateVersionWritable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TemplateVersion</returns>
        public lob.dotnet.Client.ApiResponse<TemplateVersion> createWithHttpInfo(string tmplId, TemplateVersionWritable templateVersionWritable, int operationIndex = 0)
        {
            // verify the required parameter 'tmplId' is set
            if (tmplId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'tmplId' when calling TemplateVersionsApi->create");
            }

            // verify the required parameter 'templateVersionWritable' is set
            if (templateVersionWritable == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'templateVersionWritable' when calling TemplateVersionsApi->create");
            }

            lob.dotnet.Client.RequestOptions localVarRequestOptions = new lob.dotnet.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "application/x-www-form-urlencoded",
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = lob.dotnet.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = lob.dotnet.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tmpl_id", lob.dotnet.Client.ClientUtils.ParameterToString(tmplId)); // path parameter
            localVarRequestOptions.Data = templateVersionWritable;

            localVarRequestOptions.Operation = "TemplateVersionsApi.create";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + lob.dotnet.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<TemplateVersion>("/templates/{tmpl_id}/versions", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("create", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// create Creates a new template version attached to the specified template.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template the new version will be attached to</param>
        /// <param name="templateVersionWritable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TemplateVersion</returns>
        public async System.Threading.Tasks.Task<TemplateVersion> createAsync(string tmplId, TemplateVersionWritable templateVersionWritable, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            lob.dotnet.Client.ApiResponse<TemplateVersion> localVarResponse = await createWithHttpInfoAsync(tmplId, templateVersionWritable, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// create Creates a new template version attached to the specified template.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template the new version will be attached to</param>
        /// <param name="templateVersionWritable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TemplateVersion)</returns>
        public async System.Threading.Tasks.Task<lob.dotnet.Client.ApiResponse<TemplateVersion>> createWithHttpInfoAsync(string tmplId, TemplateVersionWritable templateVersionWritable, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'tmplId' is set
            if (tmplId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'tmplId' when calling TemplateVersionsApi->create");
            }

            // verify the required parameter 'templateVersionWritable' is set
            if (templateVersionWritable == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'templateVersionWritable' when calling TemplateVersionsApi->create");
            }


            lob.dotnet.Client.RequestOptions localVarRequestOptions = new lob.dotnet.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "application/x-www-form-urlencoded", 
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = lob.dotnet.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = lob.dotnet.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tmpl_id", lob.dotnet.Client.ClientUtils.ParameterToString(tmplId)); // path parameter
            localVarRequestOptions.Data = templateVersionWritable;

            localVarRequestOptions.Operation = "TemplateVersionsApi.create";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + lob.dotnet.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<TemplateVersion>("/templates/{tmpl_id}/versions", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("create", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// delete Permanently deletes a template version. A template&#39;s &#x60;published_version&#x60; can not be deleted.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TemplateVersionDeletion</returns>
        public TemplateVersionDeletion delete(string tmplId, string vrsnId, int operationIndex = 0)
        {
            lob.dotnet.Client.ApiResponse<TemplateVersionDeletion> localVarResponse = deleteWithHttpInfo(tmplId, vrsnId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// delete Permanently deletes a template version. A template&#39;s &#x60;published_version&#x60; can not be deleted.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TemplateVersionDeletion</returns>
        public lob.dotnet.Client.ApiResponse<TemplateVersionDeletion> deleteWithHttpInfo(string tmplId, string vrsnId, int operationIndex = 0)
        {
            // verify the required parameter 'tmplId' is set
            if (tmplId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'tmplId' when calling TemplateVersionsApi->delete");
            }

            // verify the required parameter 'vrsnId' is set
            if (vrsnId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'vrsnId' when calling TemplateVersionsApi->delete");
            }

            lob.dotnet.Client.RequestOptions localVarRequestOptions = new lob.dotnet.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = lob.dotnet.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = lob.dotnet.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tmpl_id", lob.dotnet.Client.ClientUtils.ParameterToString(tmplId)); // path parameter
            localVarRequestOptions.PathParameters.Add("vrsn_id", lob.dotnet.Client.ClientUtils.ParameterToString(vrsnId)); // path parameter

            localVarRequestOptions.Operation = "TemplateVersionsApi.delete";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + lob.dotnet.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<TemplateVersionDeletion>("/templates/{tmpl_id}/versions/{vrsn_id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("delete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// delete Permanently deletes a template version. A template&#39;s &#x60;published_version&#x60; can not be deleted.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TemplateVersionDeletion</returns>
        public async System.Threading.Tasks.Task<TemplateVersionDeletion> deleteAsync(string tmplId, string vrsnId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            lob.dotnet.Client.ApiResponse<TemplateVersionDeletion> localVarResponse = await deleteWithHttpInfoAsync(tmplId, vrsnId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// delete Permanently deletes a template version. A template&#39;s &#x60;published_version&#x60; can not be deleted.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TemplateVersionDeletion)</returns>
        public async System.Threading.Tasks.Task<lob.dotnet.Client.ApiResponse<TemplateVersionDeletion>> deleteWithHttpInfoAsync(string tmplId, string vrsnId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'tmplId' is set
            if (tmplId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'tmplId' when calling TemplateVersionsApi->delete");
            }

            // verify the required parameter 'vrsnId' is set
            if (vrsnId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'vrsnId' when calling TemplateVersionsApi->delete");
            }


            lob.dotnet.Client.RequestOptions localVarRequestOptions = new lob.dotnet.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = lob.dotnet.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = lob.dotnet.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tmpl_id", lob.dotnet.Client.ClientUtils.ParameterToString(tmplId)); // path parameter
            localVarRequestOptions.PathParameters.Add("vrsn_id", lob.dotnet.Client.ClientUtils.ParameterToString(vrsnId)); // path parameter

            localVarRequestOptions.Operation = "TemplateVersionsApi.delete";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + lob.dotnet.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<TemplateVersionDeletion>("/templates/{tmpl_id}/versions/{vrsn_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("delete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// get Retrieves the template version with the given template and version ids.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TemplateVersion</returns>
        public TemplateVersion get(string tmplId, string vrsnId, int operationIndex = 0)
        {
            lob.dotnet.Client.ApiResponse<TemplateVersion> localVarResponse = getWithHttpInfo(tmplId, vrsnId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// get Retrieves the template version with the given template and version ids.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TemplateVersion</returns>
        public lob.dotnet.Client.ApiResponse<TemplateVersion> getWithHttpInfo(string tmplId, string vrsnId, int operationIndex = 0)
        {
            // verify the required parameter 'tmplId' is set
            if (tmplId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'tmplId' when calling TemplateVersionsApi->get");
            }

            // verify the required parameter 'vrsnId' is set
            if (vrsnId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'vrsnId' when calling TemplateVersionsApi->get");
            }

            lob.dotnet.Client.RequestOptions localVarRequestOptions = new lob.dotnet.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = lob.dotnet.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = lob.dotnet.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tmpl_id", lob.dotnet.Client.ClientUtils.ParameterToString(tmplId)); // path parameter
            localVarRequestOptions.PathParameters.Add("vrsn_id", lob.dotnet.Client.ClientUtils.ParameterToString(vrsnId)); // path parameter

            localVarRequestOptions.Operation = "TemplateVersionsApi.get";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + lob.dotnet.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<TemplateVersion>("/templates/{tmpl_id}/versions/{vrsn_id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("get", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// get Retrieves the template version with the given template and version ids.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TemplateVersion</returns>
        public async System.Threading.Tasks.Task<TemplateVersion> getAsync(string tmplId, string vrsnId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            lob.dotnet.Client.ApiResponse<TemplateVersion> localVarResponse = await getWithHttpInfoAsync(tmplId, vrsnId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// get Retrieves the template version with the given template and version ids.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TemplateVersion)</returns>
        public async System.Threading.Tasks.Task<lob.dotnet.Client.ApiResponse<TemplateVersion>> getWithHttpInfoAsync(string tmplId, string vrsnId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'tmplId' is set
            if (tmplId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'tmplId' when calling TemplateVersionsApi->get");
            }

            // verify the required parameter 'vrsnId' is set
            if (vrsnId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'vrsnId' when calling TemplateVersionsApi->get");
            }


            lob.dotnet.Client.RequestOptions localVarRequestOptions = new lob.dotnet.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = lob.dotnet.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = lob.dotnet.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tmpl_id", lob.dotnet.Client.ClientUtils.ParameterToString(tmplId)); // path parameter
            localVarRequestOptions.PathParameters.Add("vrsn_id", lob.dotnet.Client.ClientUtils.ParameterToString(vrsnId)); // path parameter

            localVarRequestOptions.Operation = "TemplateVersionsApi.get";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + lob.dotnet.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<TemplateVersion>("/templates/{tmpl_id}/versions/{vrsn_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("get", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// update Updates the template version with the given template and version ids.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="templateVersionUpdatable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TemplateVersion</returns>
        public TemplateVersion update(string tmplId, string vrsnId, TemplateVersionUpdatable templateVersionUpdatable, int operationIndex = 0)
        {
            lob.dotnet.Client.ApiResponse<TemplateVersion> localVarResponse = updateWithHttpInfo(tmplId, vrsnId, templateVersionUpdatable);
            return localVarResponse.Data;
        }

        /// <summary>
        /// update Updates the template version with the given template and version ids.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="templateVersionUpdatable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TemplateVersion</returns>
        public lob.dotnet.Client.ApiResponse<TemplateVersion> updateWithHttpInfo(string tmplId, string vrsnId, TemplateVersionUpdatable templateVersionUpdatable, int operationIndex = 0)
        {
            // verify the required parameter 'tmplId' is set
            if (tmplId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'tmplId' when calling TemplateVersionsApi->update");
            }

            // verify the required parameter 'vrsnId' is set
            if (vrsnId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'vrsnId' when calling TemplateVersionsApi->update");
            }

            // verify the required parameter 'templateVersionUpdatable' is set
            if (templateVersionUpdatable == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'templateVersionUpdatable' when calling TemplateVersionsApi->update");
            }

            lob.dotnet.Client.RequestOptions localVarRequestOptions = new lob.dotnet.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json",
                "application/x-www-form-urlencoded",
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = lob.dotnet.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = lob.dotnet.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tmpl_id", lob.dotnet.Client.ClientUtils.ParameterToString(tmplId)); // path parameter
            localVarRequestOptions.PathParameters.Add("vrsn_id", lob.dotnet.Client.ClientUtils.ParameterToString(vrsnId)); // path parameter
            localVarRequestOptions.Data = templateVersionUpdatable;

            localVarRequestOptions.Operation = "TemplateVersionsApi.update";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + lob.dotnet.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<TemplateVersion>("/templates/{tmpl_id}/versions/{vrsn_id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("update", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// update Updates the template version with the given template and version ids.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="templateVersionUpdatable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TemplateVersion</returns>
        public async System.Threading.Tasks.Task<TemplateVersion> updateAsync(string tmplId, string vrsnId, TemplateVersionUpdatable templateVersionUpdatable, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            lob.dotnet.Client.ApiResponse<TemplateVersion> localVarResponse = await updateWithHttpInfoAsync(tmplId, vrsnId, templateVersionUpdatable, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// update Updates the template version with the given template and version ids.
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template to which the version belongs.</param>
        /// <param name="vrsnId">id of the template_version</param>
        /// <param name="templateVersionUpdatable"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TemplateVersion)</returns>
        public async System.Threading.Tasks.Task<lob.dotnet.Client.ApiResponse<TemplateVersion>> updateWithHttpInfoAsync(string tmplId, string vrsnId, TemplateVersionUpdatable templateVersionUpdatable, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'tmplId' is set
            if (tmplId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'tmplId' when calling TemplateVersionsApi->update");
            }

            // verify the required parameter 'vrsnId' is set
            if (vrsnId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'vrsnId' when calling TemplateVersionsApi->update");
            }

            // verify the required parameter 'templateVersionUpdatable' is set
            if (templateVersionUpdatable == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'templateVersionUpdatable' when calling TemplateVersionsApi->update");
            }


            lob.dotnet.Client.RequestOptions localVarRequestOptions = new lob.dotnet.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json", 
                "application/x-www-form-urlencoded", 
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = lob.dotnet.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = lob.dotnet.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tmpl_id", lob.dotnet.Client.ClientUtils.ParameterToString(tmplId)); // path parameter
            localVarRequestOptions.PathParameters.Add("vrsn_id", lob.dotnet.Client.ClientUtils.ParameterToString(vrsnId)); // path parameter
            localVarRequestOptions.Data = templateVersionUpdatable;

            localVarRequestOptions.Operation = "TemplateVersionsApi.update";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + lob.dotnet.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<TemplateVersion>("/templates/{tmpl_id}/versions/{vrsn_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("update", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// list Returns a list of template versions for the given template ID. The template versions are sorted by creation date, with the most recently created appearing first. 
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template associated with the retrieved versions</param>
        /// <param name="limit">How many results to return. (optional, default to 10)</param>
        /// <param name="before">A reference to a list entry used for paginating to the previous set of entries. This field is pre-populated in the &#x60;previous_url&#x60; field in the return response.  (optional)</param>
        /// <param name="after">A reference to a list entry used for paginating to the next set of entries. This field is pre-populated in the &#x60;next_url&#x60; field in the return response.  (optional)</param>
        /// <param name="include">Request that the response include the total count by specifying &#x60;include[]&#x3D;total_count&#x60;.  (optional)</param>
        /// <param name="dateCreated">Filter by date created. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TemplateVersionList</returns>
        public TemplateVersionList list(string tmplId, int? limit = default(int?), string before = default(string), string after = default(string), List<string> include = default(List<string>), Dictionary<string, DateTime> dateCreated = default(Dictionary<string, DateTime>), int operationIndex = 0)
        {
            lob.dotnet.Client.ApiResponse<TemplateVersionList> localVarResponse = listWithHttpInfo(tmplId, limit, before, after, include, dateCreated);
            return localVarResponse.Data;
        }

        /// <summary>
        /// list Returns a list of template versions for the given template ID. The template versions are sorted by creation date, with the most recently created appearing first. 
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template associated with the retrieved versions</param>
        /// <param name="limit">How many results to return. (optional, default to 10)</param>
        /// <param name="before">A reference to a list entry used for paginating to the previous set of entries. This field is pre-populated in the &#x60;previous_url&#x60; field in the return response.  (optional)</param>
        /// <param name="after">A reference to a list entry used for paginating to the next set of entries. This field is pre-populated in the &#x60;next_url&#x60; field in the return response.  (optional)</param>
        /// <param name="include">Request that the response include the total count by specifying &#x60;include[]&#x3D;total_count&#x60;.  (optional)</param>
        /// <param name="dateCreated">Filter by date created. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TemplateVersionList</returns>
        public lob.dotnet.Client.ApiResponse<TemplateVersionList> listWithHttpInfo(string tmplId, int? limit = default(int?), string before = default(string), string after = default(string), List<string> include = default(List<string>), Dictionary<string, DateTime> dateCreated = default(Dictionary<string, DateTime>), int operationIndex = 0)
        {
            // verify the required parameter 'tmplId' is set
            if (tmplId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'tmplId' when calling TemplateVersionsApi->list");
            }

            lob.dotnet.Client.RequestOptions localVarRequestOptions = new lob.dotnet.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = lob.dotnet.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = lob.dotnet.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tmpl_id", lob.dotnet.Client.ClientUtils.ParameterToString(tmplId)); // path parameter
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(lob.dotnet.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (before != null)
            {
                localVarRequestOptions.QueryParameters.Add(lob.dotnet.Client.ClientUtils.ParameterToMultiMap("", "before", before));
            }
            if (after != null)
            {
                localVarRequestOptions.QueryParameters.Add(lob.dotnet.Client.ClientUtils.ParameterToMultiMap("", "after", after));
            }
            if (include != null)
            {
                localVarRequestOptions.QueryParameters.Add(lob.dotnet.Client.ClientUtils.ParameterToMultiMap("multi", "include", include));
            }
            if (dateCreated != null)
            {
                localVarRequestOptions.QueryParameters.Add(lob.dotnet.Client.ClientUtils.ParameterToMultiMap("deepObject", "date_created", dateCreated));
            }

            localVarRequestOptions.Operation = "TemplateVersionsApi.list";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + lob.dotnet.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<TemplateVersionList>("/templates/{tmpl_id}/versions", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("list", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// list Returns a list of template versions for the given template ID. The template versions are sorted by creation date, with the most recently created appearing first. 
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template associated with the retrieved versions</param>
        /// <param name="limit">How many results to return. (optional, default to 10)</param>
        /// <param name="before">A reference to a list entry used for paginating to the previous set of entries. This field is pre-populated in the &#x60;previous_url&#x60; field in the return response.  (optional)</param>
        /// <param name="after">A reference to a list entry used for paginating to the next set of entries. This field is pre-populated in the &#x60;next_url&#x60; field in the return response.  (optional)</param>
        /// <param name="include">Request that the response include the total count by specifying &#x60;include[]&#x3D;total_count&#x60;.  (optional)</param>
        /// <param name="dateCreated">Filter by date created. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TemplateVersionList</returns>
        public async System.Threading.Tasks.Task<TemplateVersionList> listAsync(string tmplId, int? limit = default(int?), string before = default(string), string after = default(string), List<string> include = default(List<string>), Dictionary<string, DateTime> dateCreated = default(Dictionary<string, DateTime>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            lob.dotnet.Client.ApiResponse<TemplateVersionList> localVarResponse = await listWithHttpInfoAsync(tmplId, limit, before, after, include, dateCreated, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// list Returns a list of template versions for the given template ID. The template versions are sorted by creation date, with the most recently created appearing first. 
        /// </summary>
        /// <exception cref="lob.dotnet.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="tmplId">The ID of the template associated with the retrieved versions</param>
        /// <param name="limit">How many results to return. (optional, default to 10)</param>
        /// <param name="before">A reference to a list entry used for paginating to the previous set of entries. This field is pre-populated in the &#x60;previous_url&#x60; field in the return response.  (optional)</param>
        /// <param name="after">A reference to a list entry used for paginating to the next set of entries. This field is pre-populated in the &#x60;next_url&#x60; field in the return response.  (optional)</param>
        /// <param name="include">Request that the response include the total count by specifying &#x60;include[]&#x3D;total_count&#x60;.  (optional)</param>
        /// <param name="dateCreated">Filter by date created. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TemplateVersionList)</returns>
        public async System.Threading.Tasks.Task<lob.dotnet.Client.ApiResponse<TemplateVersionList>> listWithHttpInfoAsync(string tmplId, int? limit = default(int?), string before = default(string), string after = default(string), List<string> include = default(List<string>), Dictionary<string, DateTime> dateCreated = default(Dictionary<string, DateTime>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'tmplId' is set
            if (tmplId == null)
            {
                throw new lob.dotnet.Client.ApiException(400, "Missing required parameter 'tmplId' when calling TemplateVersionsApi->list");
            }


            lob.dotnet.Client.RequestOptions localVarRequestOptions = new lob.dotnet.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = lob.dotnet.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = lob.dotnet.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tmpl_id", lob.dotnet.Client.ClientUtils.ParameterToString(tmplId)); // path parameter
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(lob.dotnet.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (before != null)
            {
                localVarRequestOptions.QueryParameters.Add(lob.dotnet.Client.ClientUtils.ParameterToMultiMap("", "before", before));
            }
            if (after != null)
            {
                localVarRequestOptions.QueryParameters.Add(lob.dotnet.Client.ClientUtils.ParameterToMultiMap("", "after", after));
            }
            if (include != null)
            {
                localVarRequestOptions.QueryParameters.Add(lob.dotnet.Client.ClientUtils.ParameterToMultiMap("multi", "include", include));
            }
            if (dateCreated != null)
            {
                localVarRequestOptions.QueryParameters.Add(lob.dotnet.Client.ClientUtils.ParameterToMultiMap("", "date_created", dateCreated));
            }

            localVarRequestOptions.Operation = "TemplateVersionsApi.list";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (basicAuth) required
            // http basic authentication required
            if (!string.IsNullOrEmpty(this.Configuration.Username) || !string.IsNullOrEmpty(this.Configuration.Password) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + lob.dotnet.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<TemplateVersionList>("/templates/{tmpl_id}/versions", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("list", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
