/*
 * Lob
 *
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = lob.dotnet.Client.OpenAPIDateConverter;

namespace lob.dotnet.Model
{
    /// <summary>
    /// BankAccountVerify
    /// </summary>
    [DataContract(Name = "bank_account_verify")]
    public partial class BankAccountVerify : IEquatable<BankAccountVerify>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BankAccountVerify" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public BankAccountVerify() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BankAccountVerify" /> class.
        /// </summary>
        /// <param name="amounts">In live mode, an array containing the two micro deposits (in cents) placed in the bank account. In test mode, no micro deposits will be placed, so any two integers between &#x60;1&#x60; and &#x60;100&#x60; will work. (required).</param>

        /// <summary>
        /// In live mode, an array containing the two micro deposits (in cents) placed in the bank account. In test mode, no micro deposits will be placed, so any two integers between &#x60;1&#x60; and &#x60;100&#x60; will work.
        /// </summary>
        /// <value>In live mode, an array containing the two micro deposits (in cents) placed in the bank account. In test mode, no micro deposits will be placed, so any two integers between &#x60;1&#x60; and &#x60;100&#x60; will work.</value>
        [DataMember(Name = "amounts", IsRequired = true, EmitDefaultValue = false)]
        private List<int> amounts;
        public List<int> getAmounts() {
            return amounts;
        }
        public void setAmounts(List<int> value) {
            amounts = value;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BankAccountVerify {\n");
            sb.Append("  amounts: ").Append(amounts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented, new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore });
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BankAccountVerify);
        }

        /// <summary>
        /// Returns true if BankAccountVerify instances are equal
        /// </summary>
        /// <param name="input">Instance of BankAccountVerify to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BankAccountVerify input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.amounts == input.getAmounts() ||
                    this.amounts != null &&
                    input.getAmounts() != null &&
                    this.amounts.SequenceEqual(input.getAmounts())
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.amounts != null)
                {
                    hashCode = (hashCode * 59) + this.amounts.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
