/*
 * Lob
 *
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = lob.dotnet.Client.OpenAPIDateConverter;

namespace lob.dotnet.Model
{
    /// <summary>
    /// Specifies the size of the self mailer.
    /// </summary>
    /// <value>Specifies the size of the self mailer.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SelfMailerSize
    {
        /// <summary>
        /// Enum _6x18Bifold for value: 6x18_bifold
        /// </summary>
        [EnumMember(Value = "6x18_bifold")]
        _6x18Bifold = 1,

        /// <summary>
        /// Enum _11x9Bifold for value: 11x9_bifold
        /// </summary>
        [EnumMember(Value = "11x9_bifold")]
        _11x9Bifold = 2,

        /// <summary>
        /// Enum _12x9Bifold for value: 12x9_bifold
        /// </summary>
        [EnumMember(Value = "12x9_bifold")]
        _12x9Bifold = 3

    }

}
