/*
 * Lob
 *
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using lob.dotnet.Client;
using lob.dotnet.Api;
// uncomment below to import models
//using lob.dotnet.Model;

namespace lob.dotnet.Test.Api
{
    /// <summary>
    ///  Class for testing BankAccountsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BankAccountsApiTests : IDisposable
    {
        private BankAccountsApi instance;

        public BankAccountsApiTests()
        {
            instance = new BankAccountsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BankAccountsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BankAccountsApi
            //Assert.IsType<BankAccountsApi>(instance);
        }

        /// <summary>
        /// Test BankAccountCreate
        /// </summary>
        [Fact]
        public void BankAccountCreateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BankAccountWritable bankAccountWritable = null;
            //var response = instance.BankAccountCreate(bankAccountWritable);
            //Assert.IsType<BankAccount>(response);
        }

        /// <summary>
        /// Test BankAccountDelete
        /// </summary>
        [Fact]
        public void BankAccountDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string bankId = null;
            //var response = instance.BankAccountDelete(bankId);
            //Assert.IsType<BankAccountDeletion>(response);
        }

        /// <summary>
        /// Test BankAccountRetrieve
        /// </summary>
        [Fact]
        public void BankAccountRetrieveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string bankId = null;
            //var response = instance.BankAccountRetrieve(bankId);
            //Assert.IsType<BankAccount>(response);
        }

        /// <summary>
        /// Test BankAccountVerify
        /// </summary>
        [Fact]
        public void BankAccountVerifyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string bankId = null;
            //BankAccountVerify bankAccountVerify = null;
            //var response = instance.BankAccountVerify(bankId, bankAccountVerify);
            //Assert.IsType<BankAccount>(response);
        }

        /// <summary>
        /// Test BankAccountsList
        /// </summary>
        [Fact]
        public void BankAccountsListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string before = null;
            //string after = null;
            //List<string> include = null;
            //Dictionary<string, string> dateCreated = null;
            //Dictionary<string, string> metadata = null;
            //var response = instance.BankAccountsList(limit, before, after, include, dateCreated, metadata);
            //Assert.IsType<BankAccountList>(response);
        }
    }
}
