/*
 * Lob
 *
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using lob.dotnet.Client;
using lob.dotnet.Api;
// uncomment below to import models
//using lob.dotnet.Model;

namespace lob.dotnet.Test.Api
{
    /// <summary>
    ///  Class for testing TemplatesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TemplatesApiTests : IDisposable
    {
        private TemplatesApi instance;

        public TemplatesApiTests()
        {
            instance = new TemplatesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplatesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TemplatesApi
            //Assert.IsType<TemplatesApi>(instance);
        }

        /// <summary>
        /// Test CreateTemplate
        /// </summary>
        [Fact]
        public void CreateTemplateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TemplateWritable templateWritable = null;
            //var response = instance.CreateTemplate(templateWritable);
            //Assert.IsType<Template>(response);
        }

        /// <summary>
        /// Test TemplateDelete
        /// </summary>
        [Fact]
        public void TemplateDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tmplId = null;
            //var response = instance.TemplateDelete(tmplId);
            //Assert.IsType<TemplateDeletion>(response);
        }

        /// <summary>
        /// Test TemplateRetrieve
        /// </summary>
        [Fact]
        public void TemplateRetrieveTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tmplId = null;
            //var response = instance.TemplateRetrieve(tmplId);
            //Assert.IsType<Template>(response);
        }

        /// <summary>
        /// Test TemplateUpdate
        /// </summary>
        [Fact]
        public void TemplateUpdateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string tmplId = null;
            //TemplateUpdate templateUpdate = null;
            //var response = instance.TemplateUpdate(tmplId, templateUpdate);
            //Assert.IsType<Template>(response);
        }

        /// <summary>
        /// Test TemplatesList
        /// </summary>
        [Fact]
        public void TemplatesListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string before = null;
            //string after = null;
            //List<string> include = null;
            //Dictionary<string, string> dateCreated = null;
            //Dictionary<string, string> metadata = null;
            //var response = instance.TemplatesList(limit, before, after, include, dateCreated, metadata);
            //Assert.IsType<TemplateList>(response);
        }
    }
}
