/*
 * Lob
 *
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lob.dotnet.Api;
using lob.dotnet.Model;
using lob.dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lob.dotnet.Test.Model
{
    /// <summary>
    ///  Class for testing CheckEditable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CheckEditableTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CheckEditable
        //private CheckEditable instance;

        public CheckEditableTests()
        {
            // TODO uncomment below to create an instance of CheckEditable
            //instance = new CheckEditable();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CheckEditable
        /// </summary>
        [Fact]
        public void CheckEditableInstanceTest()
        {
            // TODO uncomment below to test "IsType" CheckEditable
            //Assert.IsType<CheckEditable>(instance);
        }


        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'BankAccount'
        /// </summary>
        [Fact]
        public void BankAccountTest()
        {
            // TODO unit test for the property 'BankAccount'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Logo'
        /// </summary>
        [Fact]
        public void LogoTest()
        {
            // TODO unit test for the property 'Logo'
        }
        /// <summary>
        /// Test the property 'CheckBottom'
        /// </summary>
        [Fact]
        public void CheckBottomTest()
        {
            // TODO unit test for the property 'CheckBottom'
        }
        /// <summary>
        /// Test the property 'Attachment'
        /// </summary>
        [Fact]
        public void AttachmentTest()
        {
            // TODO unit test for the property 'Attachment'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'MergeVariables'
        /// </summary>
        [Fact]
        public void MergeVariablesTest()
        {
            // TODO unit test for the property 'MergeVariables'
        }
        /// <summary>
        /// Test the property 'SendDate'
        /// </summary>
        [Fact]
        public void SendDateTest()
        {
            // TODO unit test for the property 'SendDate'
        }
        /// <summary>
        /// Test the property 'MailType'
        /// </summary>
        [Fact]
        public void MailTypeTest()
        {
            // TODO unit test for the property 'MailType'
        }
        /// <summary>
        /// Test the property 'Memo'
        /// </summary>
        [Fact]
        public void MemoTest()
        {
            // TODO unit test for the property 'Memo'
        }
        /// <summary>
        /// Test the property 'CheckNumber'
        /// </summary>
        [Fact]
        public void CheckNumberTest()
        {
            // TODO unit test for the property 'CheckNumber'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'BillingGroupId'
        /// </summary>
        [Fact]
        public void BillingGroupIdTest()
        {
            // TODO unit test for the property 'BillingGroupId'
        }

    }

}
