/*
 * Lob
 *
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lob.dotnet.Api;
using lob.dotnet.Model;
using lob.dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lob.dotnet.Test.Model
{
    /// <summary>
    ///  Class for testing Location
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LocationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Location
        //private Location instance;

        public LocationTests()
        {
            // TODO uncomment below to create an instance of Location
            //instance = new Location();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Location
        /// </summary>
        [Fact]
        public void LocationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Location
            //Assert.IsType<Location>(instance);
        }


        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Fact]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Fact]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

    }

}
