/*
 * Lob
 *
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using lob.dotnet.Api;
using lob.dotnet.Model;
using lob.dotnet.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace lob.dotnet.Test.Model
{
    /// <summary>
    ///  Class for testing PostcardEditable
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostcardEditableTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostcardEditable
        //private PostcardEditable instance;

        public PostcardEditableTests()
        {
            // TODO uncomment below to create an instance of PostcardEditable
            //instance = new PostcardEditable();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostcardEditable
        /// </summary>
        [Fact]
        public void PostcardEditableInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostcardEditable
            //Assert.IsType<PostcardEditable>(instance);
        }


        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'MailType'
        /// </summary>
        [Fact]
        public void MailTypeTest()
        {
            // TODO unit test for the property 'MailType'
        }
        /// <summary>
        /// Test the property 'MergeVariables'
        /// </summary>
        [Fact]
        public void MergeVariablesTest()
        {
            // TODO unit test for the property 'MergeVariables'
        }
        /// <summary>
        /// Test the property 'SendDate'
        /// </summary>
        [Fact]
        public void SendDateTest()
        {
            // TODO unit test for the property 'SendDate'
        }
        /// <summary>
        /// Test the property 'Front'
        /// </summary>
        [Fact]
        public void FrontTest()
        {
            // TODO unit test for the property 'Front'
        }
        /// <summary>
        /// Test the property 'Back'
        /// </summary>
        [Fact]
        public void BackTest()
        {
            // TODO unit test for the property 'Back'
        }
        /// <summary>
        /// Test the property 'BillingGroupId'
        /// </summary>
        [Fact]
        public void BillingGroupIdTest()
        {
            // TODO unit test for the property 'BillingGroupId'
        }

    }

}
